import type { NextPage } from "next";
import Head from "next/head";

import "@fontsource/roboto/300.css";
import "@fontsource/roboto/400.css";
import "@fontsource/roboto/500.css";
import "@fontsource/roboto/700.css";
import useMediaQuery from "@mui/material/useMediaQuery";
import Controller from "../components/ControlPanel/Controller";
import Providers from "../components/ControlPanel/Providers/Providers";
import NightMode from "../components/NightMode/NightMode";
import SEO from "../components/SEO/Seo.js";

import UnderConstruction from "../components/UnderConstruction/UnderConstruction";
import Navbar from "../components/LandingPage/Navbar/Navbar";
import Hero from "../components/LandingPage/Hero/Hero";
import Footer from "../components/LandingPage/Footer/Footer";
import SignUp from "../components/LandingPage/SignUp/SignUp";
import Gallery from "../components/LandingPage/Gallery/Gallery";
const Home: NextPage = () => {
  return (
    <div>
      {" "}
      <Head>
        <title>Pattern Bay</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Hero />
      <Gallery />
      <SignUp />
      <Footer />
    </div>
  );
};

export default Home;
